name: release

on:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build
        run: make build-all
        env:
          VERSION: ${{ github.ref_name }}

      - name: Create release and upload artisacts
        run: |
          set -o errexit
          set -o pipefail
          set -o nounset
          set -o xtrace

          release_id="$(
            curl \
              -sSf \
              -X POST \
              -H "Authorization: token ${{ github.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"tag_name":"${{ github.ref_name }}","draft":false,"prerelease":false,"generate_release_notes":true}' \
              "https://api.github.com/repos/${{ github.repository }}/releases" \
              | grep -m1 '"id":' \
              | grep -o '[0-9]*'
          )"

          for f in bin/gass-*; do
            curl \
              -sSf \
              -H "Authorization: token ${{ github.token }}" \
              -H "Content-Type: $(file -b --mime-type $f)" \
              --data-binary @$f \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=$(basename $f)"
          done
