name: release

on:
  push:
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build
        run: make build-all
        env:
          VERSION: ${{ github.ref_name }}

      - name: Create Release
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"tag_name":"${{ github.ref_name }}","draft":false,"prerelease":false,"generate_release_notes":true}' \
            "https://api.github.com/repos/${{ github.repository }}/releases"

      - name: Upload Artifacts
        run: |
          for f in bin/gass-*; do
            curl \
              -H "Authorization: token ${{ github.token }}" \
              -H "Content-Type: $(file -b --mime-type $f)" \
              --data-binary @$f \
              "${{ create_release.upload_url }}?name=$(basename $f)"
          done
